### ISSUE TITLE
wp usermeta (role, etc.), woocommerce payment methods and payment tokens

### ISSUE THREAD

**Issue by alebasriner** [OliverMaerz/WordpressAuth#1]
Hi,
The module is working fine to pull/show the data from wp_users table.
But how to pull/show data from other tables as well?
Such as usermeta (role, and others), woocommerce payment methods and tokens, etc.

Thank you.

**Comment by olivermaerz** [comment]
You could add a few lines of code in lib/Auth/Source/WordpressAuth.php inside the login method and query the data you need (for example from woocomerce tables). Then pass the additional data as attributes in the SAML request (by sticking it into the attributes array towards the end of the method).
